Suppression du choix autres données sensibles
betagouv/mon-service-securise pull request #102
Opened 2022-01-21 10:18 UTC by JacquesRogueOne

Dans la page description du service,
dans la partie _Données à caractère personnel et autres données sensibles stockées par le service_,
la case à cocher **Autre données sensibles** est supprimé et à la place on intègre **Autre données sensibles** dans une zone de saisie de données sensibles

2022-01-31 15:33 UTC, egaillot requested changes

2022-01-31 15:33 UTC, egaillot commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +    .indexOf(IDENTIFIANT_AUTRE_DONNEES_SENSIBLES) !== -1
Par ailleurs, j'ai l'impression qu'on pourrait simplifier en
```javascript
donnees.descriptionService
  ?.donneesCaracterePersonnel
  ?.indexOf?.(IDENTIFIANT_AUTRES_DONNEES_SENSIBLES) > -1
```

… Mais est-ce vraiment plus lisible ? 🤔

2022-01-31 15:33 UTC, egaillot commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +const IDENTIFIANT_AUTRE_DONNEES_SENSIBLES = 'autre';
Typo : `IDENTIFIANT_AUTRES_DONNEES_SENSIBLES`

2022-01-31 15:33 UTC, egaillot commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +  );
J'ai l'impression qu'on se retrouve à faire le `push` deux fois en raison du double appel à `fonctionMiseAJour` lignes 9 et 10. Je me trompe ?

(En fait, ne ferait-on pas mieux de commencer par se débarasser de `InformationsGenerales` avant de faire cette PR ?)

2022-02-01 08:37 UTC, JacquesRogueOne commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +  );
Oui c'est vrai mais pas le choix les 2 objets sont encore là donc j'ai du faire la mise à jour 2 fois

(j'ai pas encore écrite la suppression de `informationGenerales`)

2022-02-01 11:17 UTC, egaillot commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +    .some((f) => f.description === DESCRIPTION_PAR_DEFAUT_AUTRES_DONNEES_SENSIBLES)
cf. commentaire plus haut. Peut-être qu'on peut simplifier ici de la même manière ?
```javascript
donnees.descriptionService
  ?.donneesSensiblesSpecifiques
  ?.some?.((f) => …)
```

2022-02-02 16:57 UTC, egaillot commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +const DESCRIPTION_PAR_DEFAUT_AUTRES_DONNEES_SENSIBLES = 'Autre données sensibles';
Désolé – il y a une typo que je n'avais pas vue… 😓 `'Autres données sensibles'`

2022-02-03 08:50 UTC, JacquesRogueOne commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +const DESCRIPTION_PAR_DEFAUT_AUTRES_DONNEES_SENSIBLES = 'Autre données sensibles';
<img width="463" alt="Capture d’écran 2022-02-03 à 09 49 38" src="https://user-images.githubusercontent.com/39462397/152310133-f392685c-08cf-4cb2-9f98-0e3071db2c06.png">
j'ai repris le texte du choix retiré

2022-02-03 10:44 UTC, egaillot commented on migrations/20220121083346_integreAutresDonneesSensiblesDansDonneesSensiblesSupplementaires.js
> +const DESCRIPTION_PAR_DEFAUT_AUTRES_DONNEES_SENSIBLES = 'Autre données sensibles';
Ouais… et c'est une vieille typo 😓 Il n'y a aucune raison valable pour qu'on écrive « autre » au singulier et « données » au pluriel.

2022-02-03 16:17 UTC, egaillot approved these changes
Ça me semble bon 👍

2022-02-04 13:39 UTC, merged