Ajoute un `rate-limit` sur les endpoints sensibles
betagouv/mon-service-securise pull request #1160
Opened 2023-11-14 09:46 UTC by ThibaudMZN

On souhaite ajouter du `rate-limit` plus fin sur certaines routes afin de sécuriser les points sensibles.
Les routes :
- `POST /token`
- `POST /reinitialisationMotDePasse`
- `POST /utilisateur`
- `POST /api/service`

2023-11-14 13:32 UTC, CadiChris requested changes

2023-11-14 13:32 UTC, CadiChris commented on .env.template
> +NB_REQUETE_MAX_PAR_MINUTE_ENDPOINT_SENSIBLE= # Nombre maximal de requêtes autorisées par IP et par minute pour les endpoints sensibles (connexion, inscription, modification de mot de passe, creation
Petite typo : il manque un `S` à `NB_REQUETES`

2023-11-14 13:32 UTC, CadiChris commented on .env.template
> +NB_REQUETE_MAX_PAR_MINUTE_ENDPOINT_SENSIBLE= # Nombre maximal de requêtes autorisées par IP et par minute pour les endpoints sensibles (connexion, inscription, modification de mot de passe, creation
Rajoutons que « supprimer la variable permet de désactiver la protection »

2023-11-14 13:32 UTC, CadiChris commented on src/routes/publiques/routesApiPublique.js
> +    adaptateurProtection.protectionLimiteTraficEndpointSensible(),
Ça serait chouette d'avoir des tests unitaires sur chaque route.

2023-11-14 15:30 UTC, ThibaudMZN commented on src/routes/publiques/routesApiPublique.js
> +    adaptateurProtection.protectionLimiteTraficEndpointSensible(),
Du coup c'est plus simple de mettre ça dans le middleware, je modifie les commits !

2023-11-20 10:44 UTC, CadiChris approved these changes

2023-11-20 10:58 UTC, CadiChris commented
J'ai ajouté la protection sur `COPY /api/service/:id`.

J'ai créé les variables d'env.

Je merge !

2023-11-20 10:58 UTC, merged