[SECURISER] Édition de mesure via le tiroir
betagouv/mon-service-securise pull request #1219
Opened 2023-12-15 15:29 UTC by ThibaudMZN

#### :warning: TODO: styliser le 'cartouche' de l'entête

2023-12-19 13:34 UTC, CadiChris requested changes
Il faudrait verticalement horizontalement le badge et la croix du tiroir.

![image](https://github.com/betagouv/mon-service-securise/assets/24898521/99fb3c63-bd17-40fe-be6e-e54f70f4c81f)

2023-12-19 13:50 UTC, CadiChris commented on svelte/lib/mesure/Mesure.svelte
> +    }
Vu ensemble : déplaçons ça dans un `$store` Svelte.

2023-12-19 14:01 UTC, CadiChris commented on svelte/lib/mesure/entete/EnteteTiroir.svelte
> +  }
Cette logique peut rejoindre le `$store` qui sera créé.

2023-12-19 14:05 UTC, CadiChris commented on svelte/lib/mesure/mesure.ts
> +  });
Très bonne idée ce second composant.
Peut-être le déplacer dans une fonction `changeCartoucheDuReferentiel(props.mesureAEditer)`

2023-12-19 14:06 UTC, CadiChris requested changes
Beau boulot ! Le `$store` et un alignement pour compléter.

2023-12-19 15:01 UTC, ThibaudMZN commented on svelte/lib/mesure/entete/EnteteTiroir.svelte
> +  }
Finalement, le store prend les valeurs des `mesuresExistantes`.
Donc `mesureAEditer` ne rentre pas dans le cadre de ce store.
Je ne sais pas si c'est une bonne idée de mélanger les deux.

2023-12-19 15:55 UTC, CadiChris commented on svelte/lib/mesure/Mesure.svelte
> +  import { mesureAEditerStore, store } from './mesure.store';
Essayons `mesureEnEdition` pour le nommage.

2023-12-19 16:01 UTC, CadiChris commented on svelte/lib/mesure/mesure.store.ts
> +    intitule: valeurOuChaineVide(mesureAEditer?.description),
On pourrait avoir cette logique de `valeurOuChaineVide` dans le `reinitialise` du store.

2023-12-20 08:48 UTC, ThibaudMZN commented on svelte/lib/mesure/mesure.store.ts
> +    intitule: valeurOuChaineVide(mesureAEditer?.description),
Alors après test en local, je me rends compte que c'est pas si simple.
Car en fait le `derived Store` se sert de `!mesureAEditer` pour conditionner l'affichage, or si on force des valeurs "String vide" dans le `reinitialise` du `store`, on perd l'information de "la mesure à éditer n'existe pas"

2023-12-20 09:13 UTC, CadiChris commented on svelte/lib/mesure/mesure.store.ts
> +    intitule: valeurOuChaineVide(mesureAEditer?.description),
Pourquoi pas rajouter cette abstraction dans le store ?

Et ce serait valorisé à l'initiatialisation.

enum actionEnCours = { creationSpecifique, editionSpecifique, editionGenerale }

2023-12-21 15:02 UTC, CadiChris approved these changes
C'est bon !

2023-12-21 15:03 UTC, merged