[REMANIEMENT] Création d'un nouvel objet de statistiques
betagouv/mon-service-securise pull request #1322
Opened 2024-02-06 10:16 UTC by ThibaudMZN

2024-02-06 12:30 UTC, CadiChris requested changes
Beau boulot !
Qq remarques + voyons ensemble pour l'histoire de rendre les tests de l'indice cyber plus facile à comprendre.

2024-02-06 12:30 UTC, CadiChris commented on test/modeles/statistiquesMesures.spec.js
> -      (0.8 + 0.2 * (1 / 5)) * (2 / 4),
En lisant cette assertion, je trouve que c'est plus simple pour moi quand on a des chiffres dans les `expect`. J'aimerais bien voir ce que ça donne si on utilise des chiffres dans les nouveaux tests. Avant de se pencher sur le DSL qui sera sûrement coûteux à mettre en place.

2024-02-06 12:30 UTC, CadiChris commented on test/modeles/indiceCyber.spec.js
> +    ).to.eql(indiceCyber.indiceCyber().total);
J'ai du  mal à comprendre ce que font ces `expect`. 
J'ai bien vu qu'ils étaient déjà présents dans les tests que cette PR supprime… mais même sur l'ancienne version je ne comprends pas.

2024-02-07 09:15 UTC, ThibaudMZN commented on test/modeles/indiceCyber.spec.js
> +      );
J'ai essayé de mettre en évidence le calcul de manière plus lisible, tu me diras si cela te convient :
```js
      const poidsMesuresRecommandees = coefficientRecommandees * (1 / 2);
      const poidsMesuresRecommandeesAjuste = poidsMesuresRecommandees * (2 / 3);
      const poidsMesuresIndispensables = coefficientIndispensables * (2 / 3);
      expect(indiceCyber.score('gouvernance')).to.eql(
        poidsMesuresRecommandeesAjuste + poidsMesuresIndispensables
      );
```

2024-02-07 09:25 UTC, ThibaudMZN commented on test/modeles/indiceCyber.spec.js
> +    ).to.eql(indiceCyber.indiceCyber().total);
Idem ici, j'ai essayé de rendre le test plus parlant :

```js
    const poidsMesuresGouvernance =
      indiceCyber.score('gouvernance') * nbTotalIndispensablesGouvernance;
    const poidsMesuresProtection =
      indiceCyber.score('protection') * nbTotalIndispensablesProtection;
    const nbMesuresTotal =
      nbTotalIndispensablesGouvernance + nbTotalIndispensablesProtection;

    expect(indiceCyber.indiceCyber().total).to.eql(
      noteMax *
        ((poidsMesuresGouvernance + poidsMesuresProtection) / nbMesuresTotal)
    );
```

2024-02-08 07:58 UTC, CadiChris approved these changes
_ℹ️  Fait majoritairement en binôme._

Beau boulot ! 
Le résultat vaut le coup !

2024-02-08 12:55 UTC, merged