Extrait l'entité de l'utilisateur
betagouv/mon-service-securise pull request #1378
Opened 2024-03-19 13:50 UTC by Nephtys

Afin de préparer le terrain pour sauvegarder le numéro de SIRET de l'entité de l'utilisateur. 

Une entité n'étant pas forcément publique, retire les mentions "publique" des noms des propriétés et identifiants

2024-03-19 15:47 UTC, CadiChris commented on src/modeles/utilisateur.js
> +    this.entite = new Entite(donnees.entite);
Je mettrais cette affectation **sous** l'appel à `valide()`.

2024-03-19 15:49 UTC, CadiChris commented on src/modeles/utilisateur.js
> +    };
Peut-être qu'on peut mettre cette fonction dans la classe `Entite` directement.

2024-03-19 15:55 UTC, CadiChris commented on src/vues/fragments/formulaireUtilisateur.pug
Si je tente de m'inscrire, j'ai cette erreur :

```
TypeError: /usr/src/app/src/vues/fragments/formulaireUtilisateur.pug:100
    98|           )
    99|           .message-erreur Ce champ est obligatoire. Veuillez sélectionner une entrée.
  > 100|           input(type='hidden' name='departementEntite' id='departementEntite' value != donnees.entite.departement)
    101| 
    102|       .requis
    103|         label(for = 'nomEntite-selectize') Nom de votre organisation

Cannot read properties of undefined (reading 'departement')
    at Object.pug_interp [as formulaireUtilisateur] (eval at wrap (/usr/src/app/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:283:144)
```

2024-03-19 17:11 UTC, Nephtys commented on src/modeles/utilisateur.js
> +    this.entite = new Entite(donnees.entite);
fait

2024-03-19 17:11 UTC, Nephtys commented on src/modeles/utilisateur.js
> +    };
fait

2024-03-19 17:17 UTC, Nephtys commented on src/vues/fragments/formulaireUtilisateur.pug
Résolu avec une variable avec valeur objet vide par défaut pour entite

2024-03-19 17:18 UTC, Nephtys commented
@CadiChris j'ai résolu tes commentaires, merci pour la relecture, je te laisse vérifier mes modifications quand tu auras le temps

2024-03-21 08:59 UTC, CadiChris approved these changes
Top ! 👏

2024-03-22 10:24 UTC, CadiChris requested changes
Attention @Nephtys, après test le `migrate:down` ne fonctionne pas. 
Il faut mettre les champs **DANS** `donnees`, pas à côté.

2024-03-22 10:25 UTC, CadiChris commented on migrations/20240318134323_extraitInformationsEntiteDansSousObjet.js
> +        nomEntitePublique: entite.nom,
L'erreur de migration est ici : ce serait plutôt

```js

donnees : { 
  ...autreDonnees,
  departementEntitePublique: entite.departement,
  nomEntitePublique: entite.nom 
}
```

2024-03-25 07:20 UTC, Nephtys commented on migrations/20240318134323_extraitInformationsEntiteDansSousObjet.js
> +        nomEntitePublique: entite.nom,
😬 oh je suis désolée, on a fait des modifs en relecture et je croyais avoir fait un down après aussi, je corrige ça de suite merci d'avoir trouvé l'erreur

2024-03-25 15:25 UTC, CadiChris approved these changes
Merci !

2024-03-25 15:38 UTC, merged