Sauvegarde le numéro de SIRET de l'entité de l'utilisateur.
betagouv/mon-service-securise pull request #1384
Opened 2024-03-26 08:42 UTC by Nephtys

...Le SIRET devient obligatoire afin de pouvoir identifier plus précisément l'entité de l'utilisateur. 

La saisie libre n'est plus possible. 
Le département sauvegardé n'est plus celui renseigné par l'utilisateur mais celui lié au SIRET de l'entité de l'utilisateur.

2024-03-28 09:08 UTC, CadiChris commented on src/depots/depotDonneesUtilisateurs.js
> +    donneesUtilisateur.entite = await Entite.completeDonnees(
Vu ensemble : ici dans le scénario où on invite un contributeur, ce code est appelé par `ajoutContributeurSurService` qui lui passe des `donnees` **sans** `entite`.

```
web-1  | [0] TypeError: Cannot read properties of undefined (reading 'siret')
web-1  | [0]     at Entite.completeDonnees (/usr/src/app/src/modeles/entite.js:27:70)
web-1  | [0]     at Object.nouvelUtilisateur (/usr/src/app/src/depots/depotDonneesUtilisateurs.js:50:46)
web-1  | [0]     at async creeUtilisateur (/usr/src/app/src/modeles/autorisations/ajoutContributeurSurServices.js:39:25)
web-1  | [0]     at async Object.executer (/usr/src/app/src/modeles/autorisations/ajoutContributeurSurServices.js:123:11)
web-1  | [0]     at async /usr/src/app/src/routes/privees/routesApiPrivee.js:286:9
```

Un `if` ferait sûrement l'affaire pour l'instant.

Réflexion plus profonde : créer un utilisateur lors d'une invitation est sûrement une erreur de design… on gagnerait à faire émerger un concept d'`invite` ou qqch comme ça, qui serait convertit en `utilisateur` lors de l'acceptation de l'invitation.

2024-03-28 09:14 UTC, CadiChris commented on public/utilisateur/suggestionEntite.js
> +                                            }"
Pas sûr qu'il faille laisser `data-nom` et `data-departement`, puisque désormais seul le `siret` est posté au serveur.

2024-03-28 09:18 UTC, CadiChris commented on src/depots/depotDonneesUtilisateurs.js
> +    adaptateurRechercheEntite = adapateurRechercheEntrepriseParDefaut,
Je préfère ne pas les valoriser par défaut… même si c'est l'inverse de ce que le code montre au-dessus.
On a eu des soucis où les tests se mettent à utiliser les adaptateurs par défaut (qui sont ceux de PROD) alors qu'on ne voulait pas.

On peut enlever la valeur par défaut ici ?

2024-03-28 09:19 UTC, CadiChris commented on src/modeles/entite.js
> +    adaptateurServiceAnnuaire = adaptateurRechercheEntrepriseAPI
Même remarque qu'au-dessus pour la valeur par défaut.

2024-03-28 09:23 UTC, CadiChris commented on src/modeles/entite.js
> +      return donnees;
Je serais rassuré qu'on soit alerté de ce cas qui n'est pas censé arrivé.

Peut-être loguer une erreur ici. Mais continuer à `return donnees`.

Injecter l'adaptateur, ou appeler `fabriqueAdaptateurGestionErreur()`

2024-03-28 09:31 UTC, CadiChris requested changes
Super ! Excellent premier gros chantier, merci ! Quelques changements mineurs 🙏

2024-03-28 09:38 UTC, Nephtys commented on src/depots/depotDonneesUtilisateurs.js
> +    donneesUtilisateur.entite = await Entite.completeDonnees(
j'ajoute un test dans le dépôt de données utilisateur pour vérifier que la création est possible avec juste un email

```

      it('peut créer un utilisateur avec uniquement un email', async () => {
        const utilisateur = await depot.nouvelUtilisateur({
          email: 'jean.dupont@mail.fr',
        });

        expect(utilisateur.email).to.equal('jean.dupont@mail.fr');
      });```

2024-03-28 09:39 UTC, Nephtys commented on src/depots/depotDonneesUtilisateurs.js
> +    donneesUtilisateur.entite = await Entite.completeDonnees(
(en plus du `if`)

2024-03-28 09:51 UTC, Nephtys commented on public/utilisateur/suggestionEntite.js
> +                                            }"
ça a l'air ok sans

2024-03-28 10:02 UTC, Nephtys commented on src/modeles/entite.js
> +      return donnees;
`fabriqueAdaptateurGestionErreur().logueErreur(
        new Error("Erreur lors de la recherche d'organisation par SIRET"),
        {
          siret: donnees.siret,
          reponseApiEntreprise: organisations,
        }
      );
      return donnees;`

2024-04-04 12:03 UTC, CadiChris approved these changes

2024-04-04 12:04 UTC, merged