Tache envoie mail notification expiration
betagouv/mon-service-securise pull request #1397
Opened 2024-04-03 14:27 UTC by ThibaudMZN

SENDINBLUE_TEMPLATE_NOTIFICATION_EXPIRATION_HOMOLOGATION= # id de template
SENDINBLUE_TEMPLATE_NOTIFICATION_HOMOLOGATION_EXPIREE= # id de template

[Lien du Outline](https://lab-anssi-docs.cleverapps.io/doc/emails-rappels-echeance-homologation-r4WUUFeXAD)

2024-04-04 13:57 UTC, CadiChris commented on test/taches/envoieMailsNotificationExpirationHomologation.spec.js
> +    let datePassee;
Peut-être `dateRecue` pour ne pas aller dans le champ lexical de `passé / futur` 😄

2024-04-04 13:58 UTC, CadiChris commented on test/taches/envoieMailsNotificationExpirationHomologation.spec.js
> +    let donneesPassees;
Pareil pour  `donneesRecues`.

2024-04-04 14:04 UTC, CadiChris commented on src/adaptateurs/adaptateurPersistanceMemoire.js
> +  const lisNotificationsExpirationHomologationDansInterval = async (
Typo ici `lle` à la fin.

2024-04-04 14:09 UTC, CadiChris commented on src/adaptateurs/adaptateurPersistanceMemoire.js
> +      (n) => n.dateProchainEnvoi >= dateDebut && n.dateProchainEnvoi < dateFin
Pour avoir une lecture chronologique, essayons de mettre `dateProchainEnvoi` au centre de l'expression.

2024-04-04 14:09 UTC, CadiChris commented on src/adaptateurs/adaptateurPersistanceMemoire.js
> +        (n) => n.id_service !== idService
Pas de `_` ici.

2024-04-04 14:25 UTC, CadiChris commented on src/depots/depotDonneesNotificationsExpirationHomologation.js
> +    const debut = new Date(
`const debutMinuitUtc` pour être précis.

2024-04-04 14:25 UTC, CadiChris commented on src/depots/depotDonneesNotificationsExpirationHomologation.js
> +    const fin = new Date(debut);
`const demainMinuitUtc`

2024-04-04 14:27 UTC, CadiChris commented on test/depots/depotDonneesNotificationsExpirationHomologation.spec.js
> +          donneesPassees = { debut, fin };
`const donneesRecues` ici

2024-04-04 14:32 UTC, CadiChris requested changes
Beau boulot ! Quelques changements 🙏

2024-04-04 14:39 UTC, ThibaudMZN commented on scripts/taches/tacheEnvoieMailsNotificationExpiration.js
> +    busEvenements,
On a pas besoin de ces dépendances ici.

2024-04-04 15:01 UTC, ThibaudMZN commented on scripts/taches/tacheEnvoieMailsNotificationExpiration.js
> +Sentry.withMonitor('envoie-mails-notification-expiration', () => {
`envoi` au lieu de `envoie`

2024-04-09 08:06 UTC, CadiChris approved these changes
Excellent ! Let's go !

2024-04-09 08:07 UTC, merged