Affiche un message d'information sur le tableau de services si la description du service est incomplète
betagouv/mon-service-securise pull request #1419
Opened 2024-04-16 16:27 UTC by Nephtys

...comme dans le cas du SIRET non renseigné.

Cela permet d'indiquer à l'utilisateur qu'il doit compléter sa saisie. 
Cela fait suite à l'obligation de renseigner le SIRET de l'organisation responsable du service, en l'absence de possibilité de rattrapage automatique des données.

Cette PR corrige par la même occasion le retour de statutSaisie qui avait cassé suite au changement de l'organisation responsable d'une propriété atomique à une Entite.

2024-04-17 06:21 UTC, ThibaudMZN requested changes
Petits changements, à valider avec le pôle design

2024-04-17 06:21 UTC, ThibaudMZN commented on public/assets/styles/tableauDeBord.css
> +}
Malheureusement, cette affichage ne passe pas le test d'accessibilité au niveau du contraste. Voyons si on peut corriger celà

![image](https://github.com/betagouv/mon-service-securise/assets/1643465/9707bed1-f0b1-4c43-8395-13ff2de1c8c3)

2024-04-17 06:21 UTC, ThibaudMZN commented on public/modules/tableauDeBord/tableauDesServices.mjs
> +                                   </div>`
Au passage, je me dis que l'avertissement pourrait être un lien vers la page "DÉCRIRE" pour faciliter l'UX

2024-04-18 08:36 UTC, Nephtys commented on public/assets/styles/tableauDeBord.css
> +}
<img width="235" alt="Capture d’écran 2024-04-18 à 10 36 14" src="https://github.com/betagouv/mon-service-securise/assets/308609/7d014c93-d6b0-4fff-8417-67b931c3c0ff">
avec le texte en "bleu survol" ça passerait

2024-04-18 09:09 UTC, Nephtys commented on public/assets/styles/tableauDeBord.css
> +}
<img width="828" alt="Capture d’écran 2024-04-18 à 11 07 30" src="https://github.com/betagouv/mon-service-securise/assets/308609/264b3ead-83c2-4f35-bd25-40b90633de2f">
finalement on est parti sur similaire aux bannières d'information

2024-04-18 09:10 UTC, Nephtys commented on public/assets/styles/tableauDeBord.css
> +}
<img width="242" alt="Capture d’écran 2024-04-18 à 11 09 44" src="https://github.com/betagouv/mon-service-securise/assets/308609/391372f2-8127-4b60-a313-b1c9a5e189b6">
c'est ok

2024-04-18 09:39 UTC, ThibaudMZN approved these changes
:+1:

2024-04-18 09:41 UTC, merged