MAJ page a propos
betagouv/mon-service-securise pull request #150
Opened 2022-02-21 12:25 UTC by GuillemetteJ

2022-02-21 12:29 UTC, jbdemaison requested changes
Enlever le / ligne 15 devant + d'informations

2022-02-21 12:35 UTC, jbdemaison commented
@egaillot @JacquesRogueOne je ne vois pas d'où ça vient mais dans l'affichage via le plugin Scalingo cela met "internal server error" alors qu'a priori juste le texte a été modifié...

2022-02-21 14:16 UTC, JacquesRogueOne commented on src/vues/aPropos.pug
> +        Le service est développé par la SCOP <a href="https://ut7.fr">ut7</a>
J'apprécie les collègues de l'UT7 mais est ce que ce sont encore eux qui développent le produit ?

2022-02-21 14:35 UTC, jbdemaison commented on src/vues/aPropos.pug
> +        Le service est développé par la SCOP <a href="https://ut7.fr">ut7</a>
Bonne question. 2 possibilités, soit on vous cite tous les deux explicitement mais peut-être que ce serait un peu bizarre, soit on met Omnicité ?

2022-02-21 14:44 UTC, jbdemaison commented
@egaillot tu as fait la modif liée à l'indentation ou je demande à Guillemette de la faire ? Idéalement je préfèrerais qu'elle le fasse.

2022-02-21 15:31 UTC, egaillot commented on src/vues/aPropos.pug
> +        Le service est développé par la SCOP <a href="https://ut7.fr">ut7</a>
Je pencherai pour mettre Omnicité. Mais ça me va si on met Omnicité et CodeWorks, ou encore Beta Gouv.

2022-02-21 15:31 UTC, egaillot commented
> @egaillot tu as fait la modif liée à l'indentation ou je demande à Guillemette de la faire ? Idéalement je préfèrerais qu'elle le fasse.

C'était également ma préférence, et c'est pour ça que je n'ai pas corrigé directement 😉

2022-02-21 16:27 UTC, egaillot reviewed
@GuillemetteJ – Merci pour cette soumission de PR et bienvenue parmi les contributeurs du projet 🙂 

Ce n'est pas toujours évident à détecter, mais si tu peux faire en sorte qu'il n'y ait pas d'espace en fin de ligne, ça simplifie la relecture _a posteriori_ du journal des commits.

2022-02-21 16:27 UTC, egaillot commented on src/vues/aPropos.pug
> +        de Start Up d'Etat du <a href="https://www.ssi.gouv.fr/agence/missions/rapport-dactivite-2020/">laboratoire d'innovation de l'ANSSI</a>,
Je ne suis pas sûr de mon coup, mais je trouve ce « Start Up » au singulier étrange à lire… mettre « start-ups » à la place ? Ou « services numériques publics » (comme chez Beta) ? 🤔

2022-02-21 16:27 UTC, egaillot commented on src/vues/aPropos.pug
> +        l'équipe de MonServiceSécurisé par <a href="mailto:contact@monservicesecurise.beta.gouv.fr">mail</a>.
Chacune de ces trois lignes a une espace superflue en fin de ligne. Peux-tu les supprimer s'il te plaît ?

2022-02-21 16:27 UTC, egaillot commented on src/vues/aPropos.pug
> +        et est hébergée chez <a href="https://scalingo.com">Scalingo</a> prenant
Typo : « est hébergé » (au masculin).

2022-02-21 16:27 UTC, egaillot commented on src/vues/questionsFrequentes.pug
> +          Pour protéger ces services, l'homologation de sécurité est  une
Il y a une espace en trop entre « est » et « une ».

2022-02-21 16:27 UTC, egaillot commented on src/vues/aPropos.pug
> +        appui sur le Cloud 3DS d'Outscale qualifié SecNumCloud.
Lies lignes 33 et 34 ont une espace superflue en fin de ligne.

2022-02-22 09:43 UTC, jbdemaison commented on src/vues/aPropos.pug
> +        Le service est développé par la SCOP <a href="https://ut7.fr">ut7</a>
"Par une équipe en développement et en UX design via Omnicité"
https://omnicite.fr/

2022-02-22 09:44 UTC, jbdemaison commented on src/vues/aPropos.pug
> +        Le service est développé par la SCOP <a href="https://ut7.fr">ut7</a>
Je préfère mettre ça en ne citant que l'attributaire.

2022-02-22 09:45 UTC, jbdemaison commented on src/vues/aPropos.pug
> +        de Start Up d'Etat du <a href="https://www.ssi.gouv.fr/agence/missions/rapport-dactivite-2020/">laboratoire d'innovation de l'ANSSI</a>,
Mettons services numériques

2022-02-22 09:46 UTC, jbdemaison commented on src/vues/questionsFrequentes.pug
> +          Pour protéger ces services, l'homologation de sécurité est  une
Désolé c'est une erreur introduite pour tester les commits et on ne l'a pas recorrigée.

2022-02-28 15:36 UTC, JacquesRogueOne commented
Très bon travail, bonne première Pull Request 🎉

2022-02-28 15:45 UTC, egaillot commented
> Très bon travail, bonne première Pull Request 🎉

🙌 
Merci @GuillemetteJ pour ta contribution !

2022-02-28 15:47 UTC, egaillot commented on src/vues/aPropos.pug
> +        Le service est développé par la SCOP <a href="https://ut7.fr">ut7</a>
👍

2022-02-28 15:47 UTC, egaillot commented on src/vues/aPropos.pug
> +        de Start Up d'Etat du <a href="https://www.ssi.gouv.fr/agence/missions/rapport-dactivite-2020/">laboratoire d'innovation de l'ANSSI</a>,
👍

2022-02-28 15:49 UTC, egaillot approved these changes
👍

2022-03-01 08:15 UTC, closed without merging