Déplacement entités externes Partie 1
betagouv/mon-service-securise pull request #151
Opened 2022-02-21 14:10 UTC by JacquesRogueOne

Dans l'aventure du déplacement des entités externes dans les rôles et responsabilités,
La première étape est d'enregistrer l'information dans les caractéristiques complémentaires et dans les parties prenantes.

2022-02-24 10:26 UTC, egaillot requested changes

2022-02-24 10:26 UTC, egaillot commented on src/depotDonnees.js
> +const PartiePrenanteSupplementaire = require('./modeles/partiesPrenantes/partiePrenanteSupplementaire');
Jusqu'ici, on a utilisé le terme « spécifique » pour décrire les éléments spécifiques au dossier d'homologation en cours (ex. risque spécifique, mesure spécifique, etc.). Je m'attendrais à voir ce nommage utilisé pour les « parties prenantes spécifiques » – est-ce que ça a du sens pour toi ?

2022-02-24 10:26 UTC, egaillot commented on src/depotDonnees.js
> +    }
🐛 Je pense que cette sentinelle crée une anomalie de comportement…

Si je saisis dans les caractéristiques complémentaires une entité externe, elle est correctement sauvée comme partie prenante supplémentaire. Mais si je supprime cette entité externe des caractéristiques complémentaires (et qu'il n'y a alors plus d'entité externe saisie), elle ne va pas être supprimée des parties prenantes supplémentaires.

2022-02-24 10:26 UTC, egaillot commented on src/depotDonnees.js
> +        return metsAJourProprieteHomologation('partiesPrenantes', homologationTrouvee, new PartiesPrenantes(partiesPrenantes, referentiel));
On passe `referentiel` au constructeur de `PartiesPrenantes`, mais j'ai l'impression que celui-ci ne considère comme seul argument que les données `partiesPrenantes`. Y a-t-il une raison pour laquelle on passe le référentiel ici ?

2022-02-24 10:26 UTC, egaillot commented on src/routes/routesApiHomologation.js
> +              requete.params.id, caracteristiques.entitesExternes.tous()
Ce n'est peut-être qu'une coquetterie de ma part… mais j'aurais bien envie de voir `toutes()` comme alias de `tous()`

2022-02-24 10:26 UTC, egaillot commented on test/depotDonnees.spec.js
> +        expect(partiesPrenantes.partiesPrenantes.tous().find((item) => item instanceof PartiePrenanteSupplementaire).nom).to.equal('nom');
De la même manière qu'on a utilise une fonction `PartiesPrenantes#hebergement()`, je m'attendrais à voir ici un appel à `partiesPrenantes.partiesPrenantes.supplementaires()`.

2022-02-24 13:52 UTC, JacquesRogueOne commented on src/depotDonnees.js
> +const PartiePrenanteSupplementaire = require('./modeles/partiesPrenantes/partiePrenanteSupplementaire');
j'ai mis **spécifique** partout

2022-02-24 14:16 UTC, egaillot commented on src/depotDonnees.js
> +const PartiePrenanteSupplementaire = require('./modeles/partiesPrenantes/partiePrenanteSupplementaire');
🙏

2022-02-24 14:53 UTC, JacquesRogueOne commented on src/depotDonnees.js
> +    }
oui bien vu je l'ai retirée

2022-02-25 09:32 UTC, egaillot approved these changes
Il reste une typo sur la description d'un des tests, mais le reste me semble bon 👍

2022-02-25 09:32 UTC, egaillot commented on test/depotDonnees.spec.js
> +  it('ne met pas à jour les parties prenantes avec avec des entités externes vides', (done) => {
Typo : il y a un « avec » en trop

2022-02-28 09:26 UTC, merged