Ajoute une route pour mettre à jour une mesure générale
betagouv/mon-service-securise pull request #1556
Opened 2024-06-24 15:39 UTC by Nephtys

... de façon unitaire, afin d'ensuite pouvoir remplacer la mise à jour de toutes les mesures d'une seule requête par la mise à jour indépendante de chaque mesure.

2024-06-24 19:56 UTC, ThibaudMZN requested changes
Une petite modification à faire, un doublon qu'on a pas vu au moment du refactoring !
Sinon, tout est nickel :)

2024-06-24 19:56 UTC, ThibaudMZN commented on src/modeles/mesuresGenerales.js
> +    const mesure = new MesureGenerale(donneesMesure, this.referentiel);
En fait, le constructeur de `MesureGenerale` effectue déjà la validation `MesureGenerale.valide()`.
Donc la ligne 16 est ici redondante avec la ligne 18.
On peut supprimer la l.16

2024-06-25 15:28 UTC, CadiChris commented on src/routes/connecte/routesConnecteApiService.js
> +        reponse.sendStatus(200);
En discutant avec @Nephtys : 
 - on voudrait garder l'approche `entité qui se mute`, donc la fonction `service.metAJourMesure({`, puis le `depot.metsAJourService`
 - il manque ici l'appel au bus d'événements

On n'est pas trop fan d'avoir l'API qui sait appeler le bus d'événement.

Idée :
 - on délègue au dépôt de données la procédure complète (charger le service par id, le muter, le sauvegarder, puis publier sur le bus)

Pseudo code 

```js
async function metsAJourUneMesureGenerale(idService, mesure {id, donnees}, idUtilisateur) {
  const s = await lisService(idService)
  s.metAJourMesure(mesure)
  await metsAJourService(s)
  bus.publie(new Evenement…())
}
```

2024-07-02 06:34 UTC, closed without merging

2024-07-02 06:35 UTC, Nephtys commented
j'ai recréé une branche propre, les rebase avaient trop modifié l'historique