[PLAN D'ACTION] Ajout du "Toaster" pour les changements de statuts
betagouv/mon-service-securise pull request #1605
Opened 2024-07-17 13:05 UTC by ThibaudMZN

2024-07-18 08:19 UTC, fbezagu commented on svelte/lib/tableauDesMesures/TableauDesMesures.svelte
> -    background-image: url('/statique/assets/images/icone_enregistrement_termine.svg');
Est-ce qu’on se sert encore de cette icône ?

2024-07-18 08:22 UTC, fbezagu commented on svelte/lib/ui/animations/transitions.ts
> +    tick: (t: number, u: number) => {
nommer t et u

2024-07-18 08:24 UTC, fbezagu requested changes
Superbes, juste quelques changements ;)

2024-07-18 08:55 UTC, ThibaudMZN commented on svelte/lib/tableauDesMesures/TableauDesMesures.svelte
> -    background-image: url('/statique/assets/images/icone_enregistrement_termine.svg');
Bien vu !

2024-07-19 07:29 UTC, fbezagu approved these changes

2024-07-19 08:04 UTC, fbezagu approved these changes
super, au pixel près

2024-07-19 08:18 UTC, merged