[AGENT CONNECT] Inscription via Agent Connect
betagouv/mon-service-securise pull request #1791
Opened 2024-09-12 13:34 UTC by Nephtys

Lors de la connexion OIDC Agent Connect, si le compte n'existe pas dans MSS, on le crée via la page d'inscription, avec les champs nom/prénom/email/siret pré remplis

2024-09-12 14:19 UTC, ThibaudMZN requested changes
2 petits changements, rien de très dur !

2024-09-12 14:23 UTC, Nephtys commented on src/routes/nonConnecte/routesNonConnecteOidc.js
> +        reponse.render('apresAuthentification', { mode: 'connexion' });
aucune idée, je n'ai pas souvenir de ça. @fbezagu ?

2024-09-12 14:23 UTC, Nephtys commented on src/routes/nonConnecte/routesNonConnecteApi.js
> +          if (!requete.body.ac) {
même si on teste juste la présence et ne lit pas le contenu ?

2024-09-12 14:31 UTC, ThibaudMZN commented on src/routes/nonConnecte/routesNonConnecteApi.js
> +          if (!requete.body.ac) {
Ben... C'est une bonne remarque !
Je retire mon commentaire

2024-09-12 14:52 UTC, ThibaudMZN approved these changes

2024-09-12 15:18 UTC, CadiChris commented on public/inscription.js
> +  if (ac) {
J'aimerais bien qu'on explicite `agentConnect` plutôt que `ac`

2024-09-12 15:20 UTC, CadiChris commented on src/routes/nonConnecte/routesNonConnecteApi.js
> +          }
J'ai l'intuition qu'ici on pourrait avoir une abstraction de finalisation d'inscription… qui aurait une version `source MSS` et une version `source OIDC("AgentConnect")`.

La différence entre inscription MSS et AgentConnect pourrait ne pas se limiter à l'envoi ou non du mail de finalisation. Le fait d'avoir encore un MDP et un ID RESET MDP pour les AgentConnectés, je trouve ça étrange.

2024-09-13 07:28 UTC, fbezagu commented on src/routes/nonConnecte/routesNonConnecteApi.js
> +          }
Oui, tout à fait d’accord. Par contre, je pense qu’il faut attendre le merge de la PR #1792 pour faire ce soin.

2024-09-13 07:32 UTC, fbezagu commented on public/inscription.js
> +  if (ac) {
Fait

2024-09-16 08:11 UTC, CadiChris approved these changes
Super !

2024-09-16 08:20 UTC, merged