Suppression de l'ancienne fonctionnalité Autres
betagouv/mon-service-securise pull request #25
Opened 2021-12-21 13:35 UTC by JacquesRogueOne

Dans la page Informations générales,
nous avons mis à disposition une possibilité pour renseigner les _autres fonctionnalités_
Le choix _Autres fonctionnalités permettant des échanges de données_ va disparaitre
À la place il y aura un champ dans _autres fonctionnalités_ avec la valeur _Autres fonctionnalités permettant des échanges de données_

2021-12-23 23:10 UTC, egaillot requested changes
Le script de migration me semble à revoir.

2021-12-23 23:10 UTC, egaillot commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  if (!Array.isArray(informationsGenerales.fonctionnalitesSpecifiques) || informationsGenerales.fonctionnalites.indexOf({ description: 'Autres fonctionnalités permettant des échanges de données' }) =
Je serais surpris que ce code fonctionne… D'une part, tu cherches dans la liste des `informationsGenerales.fonctionnalites` alors qu'il faudrait chercher je pense dans les `informationsGenerales.fonctionnalitesSpecifiques`. D'autre part, tu cherches à retrouver un objet dans une liste en le comparant à un nouvel objet :
```javascript
[{ a: 42 }, { b: 59 }].indexOf({ a: 42 }) // retourne -1
```

À vérifier si ça marche, mais je m'attendrais à voir plutôt quelque chose comme…
```javascript
informationsGenerales.fonctionnalitesSpecifiques
  .flatMap((f) => Object.values(f))
  .indexOf(DESCRIPTION_PAR_DEFAUT_AUTRES_FONCTIONNALITES)
```

2021-12-23 23:10 UTC, egaillot commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  informationsGenerales.fonctionnalitesSpecifiques.push({ description: 'Autres fonctionnalités permettant des échanges de données' });
Vu que tu réutilises le texte à plusieurs endroits de la migrations, je serais d'avis de l'extraire dans une constante, par exemple `DESCRIPTION_PAR_DEFAUT_AUTRES_FONCTIONNALITES`.

2021-12-23 23:10 UTC, egaillot commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  informationsGenerales.fonctionnalitesSpecifiques.filter((fonctionnalite) => fonctionnalite !== { description: 'Autres fonctionnalités permettant des échanges de données' });
Cf. commentaire ci-dessus. Je serais surpris que le filtre fonctionne.

2021-12-24 11:11 UTC, JacquesRogueOne commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  if (!Array.isArray(informationsGenerales.fonctionnalitesSpecifiques) || informationsGenerales.fonctionnalites.indexOf({ description: 'Autres fonctionnalités permettant des échanges de données' }) =
ce que je cherche dans ce **if** :
- savoir si il n'y a pas de fonctionnalités spécifiques renseignées
- dans les fonctionnalités non spécifique savoir si _Autres fonctionnalités ..._ n'y est pas
Comme ça a pas été clair je vais changer un peu

2021-12-24 13:32 UTC, JacquesRogueOne commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  informationsGenerales.fonctionnalitesSpecifiques.filter((fonctionnalite) => fonctionnalite !== { description: 'Autres fonctionnalités permettant des échanges de données' });
en plus il y a pas d'assignation donc ce filter ne sert pas :(

2021-12-24 14:17 UTC, JacquesRogueOne commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  if (!Array.isArray(informationsGenerales.fonctionnalitesSpecifiques) || informationsGenerales.fonctionnalites.indexOf({ description: 'Autres fonctionnalités permettant des échanges de données' }) =
👍

2021-12-24 14:17 UTC, JacquesRogueOne commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  informationsGenerales.fonctionnalitesSpecifiques.filter((fonctionnalite) => fonctionnalite !== { description: 'Autres fonctionnalités permettant des échanges de données' });
👍

2021-12-24 14:18 UTC, JacquesRogueOne commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  informationsGenerales.fonctionnalitesSpecifiques.push({ description: 'Autres fonctionnalités permettant des échanges de données' });
👍

2021-12-24 14:18 UTC, JacquesRogueOne commented on migrations/20211216163509_integreAutreFonctionnaliteAvecFonctionnalitesSpecifiques.js
> +  if (!Array.isArray(informationsGenerales.fonctionnalitesSpecifiques) || informationsGenerales.fonctionnalites.indexOf({ description: 'Autres fonctionnalités permettant des échanges de données' }) =
j'ai utilisé un `array.some()`

2021-12-26 20:50 UTC, egaillot requested changes
Il n'y a pas de fonction `some` pour les `fonctionnalitesSpecifiques` - ce qui fait planter la migration descendante 🙁 As-tu vérifié que la migration marchait avant de soumettre la PR ?

2021-12-26 20:56 UTC, egaillot commented
> Il n'y a pas de fonction some pour les fonctionnalitesSpecifiques - ce qui fait planter la migration descendante 🙁

C'est moi qui est mal lu. Mes excuses pour le bruit.

2021-12-26 20:57 UTC, egaillot reviewed
… Je continue de 👀

2021-12-26 21:40 UTC, egaillot approved these changes
👍 
J'ai modifié le script de migration pour le rendre (je l'espère) plus lisible.

2021-12-26 21:46 UTC, merged