Modale de déconnexion multi fenêtres
betagouv/mon-service-securise pull request #291
Opened 2022-06-09 15:48 UTC by JacquesRogueOne

Quand un utilisateur est connecté sur plusieurs onglets / fenêtres,
les modales notifiant la déconnexions doivent être synchronisées

NOTE : utilisation d'une variable dans le localStorage coté client

2022-07-14 14:19 UTC, egaillot approved these changes
Cool 🙂 
J'ai l'impression que c'est galère d'ajouter deux tests qui vérifient le comportement de ce code… Si tu vois une manière simple de le faire, n'hésite pas. Sinon, ça me va qu'on fusionne tel quel.

2022-07-14 14:21 UTC, egaillot requested changes
J'ai oublié un truc, désolé… 😓
Cf. commentaire sur utilisation API de `localStorage`.

2022-07-14 14:24 UTC, egaillot requested changes

2022-07-14 14:24 UTC, egaillot commented on public/modules/deconnexion.js
> +  localStorage.heureDeconnexion = new Date(Date.now() + dureeSession).valueOf();
Cf. remarque ci-dessus : je préfèrerais qu'on utilise l'API `localStorage.setItem` (https://developer.mozilla.org/en-US/docs/Web/API/Storage/setItem)

2022-07-14 14:24 UTC, egaillot commented on public/modules/deconnexion.js
> +  if (Date.now() >= localStorage.heureDeconnexion) {
Je suis surpris qu'on n'utilise pas ici l'API de localStorage (cf. https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem). Ça me semblerait quand même plus propre que d'ajouter une propriété à un objet global.

2022-07-15 15:17 UTC, JacquesRogueOne commented
Pour les tests c'est assez complexe car setTimeout et Date.now() sont aussi utilisé par mocha donc il faudrait que je modifie le code pour ne pas à avoir à trafiquer le scope global (oui je sais c'est mal 🙂)

2022-07-15 21:11 UTC, egaillot approved these changes
Une possible suggestion, mais rien qui n'empêche le merge.

2022-07-15 21:11 UTC, egaillot commented on public/modules/deconnexion.js
> +    setTimeout(lanceDecompteAffichage, localStorage.getItem('heureDeconnexion') - Date.now());
Peut-être utiliser une constante plutôt que la chaîne littérale ?… Par exemple `localStorage.getItem(HEURE_DECONNEXION)`.

2022-07-15 21:12 UTC, egaillot commented
> Pour les tests c'est assez complexe car setTimeout et Date.now() sont aussi utilisé par mocha donc il faudrait que je modifie le code pour ne pas à avoir à trafiquer le scope global (oui je sais c'est mal 🙂)

👍 Restons-en là pour l'instant.

2022-07-18 07:24 UTC, merged