Mise en avant des champs saisis
betagouv/mon-service-securise pull request #320
Opened 2022-08-02 15:20 UTC by JacquesRogueOne

Dans la page d'inscription,
Quand un champ texte est rempli ou un champ à liste de choix est sélectionné,
Le conteneur du champ doit apparaitre en bleu comme dans l'UI kit
<img width="530" alt="Capture d’écran 2022-08-02 à 17 19 59" src="https://user-images.githubusercontent.com/39462397/182411055-ffab6db1-27c1-4fa8-bdf8-290ffae2a55d.png">

2022-08-02 17:30 UTC, egaillot requested changes
Dans certains contextes, le comportement n'est pas celui attendu (cf. commentaires de relecture).

2022-08-02 17:30 UTC, egaillot commented on public/inscription.js
> +  const brancheMiseEnAvantSaisis = () => $("input[type!='radio'][type!='checkbox'], select")
typo : `brancheMiseEnAvantSaisie`

2022-08-02 17:30 UTC, egaillot commented on public/inscription.js
> +    .on('change', (evenement) => $(evenement.target).toggleClass('champ-saisi', evenement.target.value));
Le deuxième argument de `toggleClass` doit être un booléen, pas juste un truthy / falsy. (cf. https://api.jquery.com/toggleClass/)

Dans l'état actuel, si jamais on saisit `A` dans un champ, qu'on sort, puis qu'on saisit `Aa`, le liseré bleu disparaît. Si ensuite on supprime la saisie dans ce même champ, le liseré bleu apparaît (comportement contraire à ce qu'on veut).

Si on écrit `…toggleClass('champ-saisi', !!evenement.target.value)` le comportement semble correct.

2022-08-03 08:46 UTC, JacquesRogueOne commented on public/inscription.js
> +  const brancheMiseEnAvantSaisis = () => $("input[type!='radio'][type!='checkbox'], select")
Quand je l'ai écrit je pensais _branche la mise en avant des champs saisis_ mais je reconnais que c'était pas assez clair.

2022-08-03 08:51 UTC, JacquesRogueOne commented on public/inscription.js
> +    .on('change', (evenement) => $(evenement.target).toggleClass('champ-saisi', evenement.target.value));
je vais être plus expressif avec `evenement.target.value !== ''`

2022-08-04 13:45 UTC, egaillot commented on public/inscription.js
> +    .on('change', (evenement) => $(evenement.target).toggleClass('champ-saisi', evenement.target.value));
Je suis un peu nerveux à l'idée qu'on ne traiterait pas le cas où `evenement.target.value` renverrait `undefined`… mais ça fait le boulot en l'état.

2022-08-04 14:13 UTC, egaillot commented on public/inscription.js
> +    .on('change', (evenement) => $(evenement.target).toggleClass('champ-saisi', evenement.target.value));
Je découvre une piste différente, mais qui serait peut-être plus idiomatique serait de passer par la pseudo classe `:valid` (cf. https://developer.mozilla.org/en-US/docs/Web/CSS/:valid). Peut-être à mettre en place dans cette PR, ou dans une PR différente.

2022-08-04 14:14 UTC, egaillot approved these changes
Ce `.on('change')` ne me satisfait pas complètement (cf. piste proposée avec `:valid`) mais peut-être que c'est suffisant pour l'instant.

2022-08-04 14:47 UTC, JacquesRogueOne commented on public/inscription.js
> +    .on('change', (evenement) => $(evenement.target).toggleClass('champ-saisi', evenement.target.value));
Je viens de lire et tester :valid et c'est pas exactement le comportement que je souhaitais, je cherchais à mettre en évidence quand un champ est rempli, avec valid cela mettra en évidence un champ qui répond aux règles (required min max pattern). On peut avoir le même résultat en ajoutant dans les inputs _pattern=".+" required_.
Pour le moment je serais pour laisser avec la technique à l'ancienne mais dès que l'on nous demandera des validateurs de formes d'emails / numéros ou noms ce sera bien vu d'utiliser les pseudo-class css + attributs html de validations

2022-08-04 16:30 UTC, egaillot commented on public/inscription.js
> +    .on('change', (evenement) => $(evenement.target).toggleClass('champ-saisi', evenement.target.value));
Ça marche. Faisons comme ça.

2022-08-05 07:38 UTC, merged