Changement "autre" par "hors de l'union européenne"
betagouv/mon-service-securise pull request #347
Opened 2022-08-30 13:38 UTC by jbdemaison

2022-08-31 08:12 UTC, JacquesRogueOne reviewed
Comme nous essayons de conserver une cohérence entre l'affichage et les données persistées, cette modification devra impérativement être suivie d'une migration de données car la clé **autre** n'a plus de sens.
Je crée une carte Trello pour cela 👍🏼

2022-08-31 08:12 UTC, JacquesRogueOne commented on donneesReferentiel.js
> +    autre: { description: "Hors de l'Union européenne" },
Dans le choix **Union Européenne**, européenne est écrit avec un E majuscule et ici non. Quelle est la bonne formulation ? Est-ce que tu pourrais uniformiser l'écriture

2022-09-01 08:25 UTC, egaillot commented on donneesReferentiel.js
> +    autre: { description: "Hors de l'Union européenne" },
J'ai l'impression qu'il n'en faut pas – https://fr.wikipedia.org/wiki/Union_europ%C3%A9enne

Par conséquent, il faudrait surtout corriger la ligne 606.

2022-09-01 08:49 UTC, egaillot commented on donneesReferentiel.js
> +    autre: { description: "Hors de l'Union européenne" },
> Par conséquent, il faudrait surtout corriger la ligne 606 😅

C'est fait 😉

2022-09-01 08:52 UTC, JacquesRogueOne approved these changes

2022-09-01 13:32 UTC, egaillot requested changes
À vérifier – j'ai l'impression que finalement les textes seraient « Hors Union européenne »

2022-09-05 10:33 UTC, egaillot approved these changes

2022-09-05 10:55 UTC, merged