Icône de danger pour les messages d'erreurs
betagouv/mon-service-securise pull request #350
Opened 2022-09-02 13:18 UTC by JacquesRogueOne

Dans les formulaires ayants de la validation (inscription, édition)
Les messages d'erreurs s'afficheront avec une icône ⚠
<img width="458" alt="Capture d’écran 2022-09-02 à 15 09 26" src="https://user-images.githubusercontent.com/39462397/188153702-63d2f9f1-9111-45da-8be2-34e585570acc.png">

NOTE : le texte a été remis à la taille normale

2022-09-05 10:40 UTC, egaillot commented
L'affichage ne colle pas sous Firefox 😓

<img width="287" alt="Screenshot 2022-09-05 at 12 38 46" src="https://user-images.githubusercontent.com/105624/188430453-72994b62-0857-4ffd-97c1-6d339782d773.png">

2022-09-05 10:44 UTC, egaillot requested changes

2022-09-05 10:44 UTC, egaillot commented on public/assets/styles/modules/validation.css
> +  content: '\0026A0';
Le caractère s'affiche plus gros sur Firefox, ce qui empiète sur le texte… Peut-être qu'il serait plus judicieux de passer par une icône SVG.

2022-09-05 14:02 UTC, JacquesRogueOne commented on public/assets/styles/modules/validation.css
> +  content: '\0026A0';
J'ai pris le svg de Figma

2022-09-06 07:35 UTC, egaillot commented on public/assets/styles/modules/validation.css
> +  content: '\0026A0';
Les icônes ne sont plus alignées avec le bord du cadre, c'est normal ?
Par ailleurs, je laisserais bien un peu plus d'espace entre l'icône et le texte.

2022-09-06 07:41 UTC, egaillot commented on public/assets/styles/modules/validation.css
> +  content: '\0026A0';
(Cf. maquette)

2022-09-07 19:30 UTC, egaillot approved these changes
Ça me semble bon 👍

2022-09-08 09:02 UTC, merged