Espace personnel modale d attestation
betagouv/mon-service-securise pull request #386
Opened 2022-09-29 12:42 UTC by ColinGarrigaSalaun

2022-09-29 13:58 UTC, egaillot commented
Le message de warning me semble long et déroutant… Par ailleurs je ne le vois pas dans les maquettes. Peux-tu m'en dire plus sur sa raison d'être ici ?

2022-09-29 14:02 UTC, ColinGarrigaSalaun commented
> Le message de warning me semble long et déroutant… Par ailleurs je ne le vois pas dans les maquettes. Peux-tu m'en dire plus sur sa raison d'être ici ?

Oui, ce sont les indications que j'ai trouvé en détails du document de sprint : https://docs.google.com/document/d/1Zg8WAFuGxfslS40gXbOTT0zm2rq0Fp5CXFd5nQ1rLmA/edit

2022-09-29 20:47 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +               .message.message-erreur
Le message d'erreur n'est pas celui auquel je m'attendrais… plus quelque chose comme « Ce champ est obligatoire. Veuillez le cocher. » Je ne le trouve pas non plus sur les maquettes – mais je ne regarde peut-être pas au bon endroit 🤔

2022-09-29 20:47 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +                 a(href='/questionsFrequentes#services-exclus', target='_blank', rel='noopener').nouvel-onglet (en savoir plus)
J'aimerais bien voir un mixin ici (par exemple `+lienNouvelOnglet('/questionsFrequentes#services-exclus', '(en savoir plus)').

2022-09-29 21:13 UTC, egaillot commented
> Oui, ce sont les indications que j'ai trouvées en détails du document de sprint

Merci. C'est plus clair pour moi. J'ai l'impression qu'on mélange deux choses :
1. l'astérisque à gauche de la case, qui signifie que le champ est obligatoire, et pour laquelle il faut afficher un message d'erreur (même comportement que si on souhaite créer un compte utilisateur sans cocher la case « j'accepte les CGU »), et
2. l'astérisque en fin de texte, qui suggère un renvoi et un bout de texte supplémentaire. Je suggèrerais (en l'absence de maquette) une bulle d'aide, du type de celle qu'on affiche quand on survole avec la souris le disque d'un collaborateur dans la page Espace personnel.

Pour ce deuxième cas, demander l'avis de notre designer serait probablement bienvenu.

2022-09-30 08:21 UTC, egaillot commented
Vu à l'oral ce matin –
1. On enlève le texte complémentaire en rouge
2. On ne met pas de message d'erreur
3. On grise le bouton tant que la case n'est pas cochée.

2022-09-30 14:32 UTC, egaillot requested changes
Gros boulot, merci !
Il y a encore quelques trucs qui me chiffonnent et que j'aimerais bien voir réglés avant d'accepter la PR :
- débordement du formulaire de la modale
- gestion du bouton quand il est grisé

… Les autres suggestions sont plus cosmétiques et soumises à ton meilleur jugement.

2022-09-30 14:32 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +      form.etroit(action="/homologation/creation", method="GET")
Le fait que tu utilises un `form.etroit` plutôt qu'un simple `form` engendre une « compétition » entre la modale qui fixe une taille de 600px, et les choses étroites qui ont une taille fixe de 400px. Cela engendre un « débordement » du formulaire de la modale.

Je suggère d'écrire ici `form(action = …, method = …)`

(voir aussi les commentaires concernant `espacePersonnel.css`.)

2022-09-30 14:32 UTC, egaillot commented on public/assets/styles/espacePersonnel.css
> +}
Cette surcharge de `modale.css` n'est pas top… et ne sert pas à grand chose en fait :) Si on n'utilise pas `form.etroit` mais simplement `form`, on devrait pouvoir se passer de ce sélecteur.

2022-09-30 14:32 UTC, egaillot commented on public/assets/styles/espacePersonnel.css
> +}
Là aussi, on se retrouve à redéfinir un style existant dans `modale.css`, mais c'est dépendant de l'ordre dans lequel on fait les déclarations, ce qui est fragile.

Est-on obligé d'utiliser une section ici, si c'est pour qu'elle ne ressemble pas à une section ? Je comprends qu'on veut bénéficier du padding et de l'alignement à gauche, mais j'imagine qu'on devrait pouvoir caser ça dans `modale.css` sur une balise plus générique.

2022-09-30 14:32 UTC, egaillot commented on public/assets/styles/espacePersonnel.css
> +}
Ce code est dupliqué avec celui de `utilisateur.css`. Il y a probablement un intérêt à déplacer les sélecteurs concernant les cases à cocher dans `form.css`

2022-09-30 14:32 UTC, egaillot commented on src/vues/fragments/lienNouvelOnglet.pug
> +  link(href='/statique/assets/styles/modules/lienNouvelOnglet.css', rel='stylesheet')
Par convention dans les fichiers pug, on préfère laisser des espaces autour des `=` :
```javascript
link(href = '/statique/assets/styles/modules/lienNouvelOnglet.css', rel = 'stylesheet')
```

(… Et c'est possible qu'il reste des endroits où on n'a pas fait ça correctement 😓 )

2022-09-30 14:32 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +          .requis(data-nom='attestation')
Est-on obligé ici de renseigner un `data-nom` ?

2022-09-30 14:32 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +            .case-a-cocher
J'aurais envie de voir ce que ça donne si on met `.case-a-cocher.requis` sur une seule div… Est-ce que ça marche ?

2022-09-30 14:32 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +      form.etroit(action="/homologation/creation", method="GET")
Sinon (cf. commentaire plus haut) : ça serait bien de mettre des espaces autour des `=` – sur cette ligne et plus bas dans ce fichier.

2022-09-30 14:32 UTC, egaillot commented on public/modules/modaleNouveauService.js
> +    }
… Et – à voir – il y a peut-être moyen de passer par le renseignement de la propriété `disabled` :
```javascript
checkbox.on('click', () => button.prop('disabled', () => !checkbox.prop('checked')));
```

2022-10-03 12:08 UTC, ColinGarrigaSalaun commented on public/modules/interactions/modale.mjs
> +};
:+1:

2022-10-03 12:13 UTC, ColinGarrigaSalaun commented on public/modules/modaleNouveauService.js
> +  const button = $('#modale-nouveau-service button[type=submit]');
:+1: 

J'aime bien cette convention aussi.

2022-10-03 12:18 UTC, ColinGarrigaSalaun commented on public/modules/modaleNouveauService.js
> +  const form = $('#modale-nouveau-service form');
:+1: 

J'ai préféré la factorisation avec "find" qui m'a semblé plus claire : $form = $modale.find('form');

2022-10-03 12:24 UTC, ColinGarrigaSalaun commented on public/modules/modaleNouveauService.js
> +    }
Merci, je n'avais pas vu que le changement d'URL n'était plus nécessaire.

Je ne suis pas allé jusqu'à réduire le bloc à une seule ligne, Le lecture serait plus concise mais moins lisible à mon avis.

Je n'ai pas réussi à générer d'attribut unaire "disabled" avec pug, du coup je m'en passe dans la solution actuelle.

2022-10-03 12:41 UTC, ColinGarrigaSalaun commented on public/assets/styles/formulaire.css
> +}
:+1:

2022-10-03 13:02 UTC, ColinGarrigaSalaun commented on src/vues/fragments/modaleNouveauService.pug
> +          .requis(data-nom='attestation')
:+1: 

Ah ben non :)

2022-10-03 13:02 UTC, ColinGarrigaSalaun commented on src/vues/fragments/lienNouvelOnglet.pug
> +  link(href='/statique/assets/styles/modules/lienNouvelOnglet.css', rel='stylesheet')
:+1:

2022-10-03 13:03 UTC, ColinGarrigaSalaun commented on src/vues/fragments/modaleNouveauService.pug
> +            .case-a-cocher
:+1:  - Ca fonctionne !

2022-10-03 13:04 UTC, ColinGarrigaSalaun commented on public/assets/styles/espacePersonnel.css
> +}
:+1:

2022-10-03 13:12 UTC, ColinGarrigaSalaun commented on src/vues/fragments/modaleNouveauService.pug
> +      form.etroit(action="/homologation/creation", method="GET")
:+1:

2022-10-03 13:12 UTC, ColinGarrigaSalaun commented on public/assets/styles/espacePersonnel.css
> +}
:+1:

2022-10-03 21:05 UTC, egaillot commented on public/assets/styles/bouton.css
> +  cursor: default;
Là aussi, ça fait le boulot… mais c'est dommage de commencer par déclarer un style sur `.bouton:hover` pour ensuite venir annuler la valeur dans `.bouton.inactif:hover`. Pour des questions de concision, de lisibilité et de maintenabilité, ça serait peut-être miuex de changer le sélecteur `.bouton:hover` en quelque chose comme
```javascript
.bouton:not(.inactif):hover {
  cursor: pointer;
  opacity: .87;
}
```

2022-10-03 21:06 UTC, egaillot commented on public/modules/modaleNouveauService.js
> +    }
… Sauf que malheureusement le bouton n'est pas désactivé, du coup :(

2022-10-03 21:18 UTC, egaillot commented on public/modules/modaleNouveauService.js
> +    }
Pour générer l'attribut `disabled`, tu peux écrire `button(type = 'submit', disabled)`.
(cf. https://pugjs.org/language/attributes.html)

(Note – pour une raison pas claire et contrairement à ce qui est mis dans la doc, j'ai l'impression qu'on génère malgré tout un `disabled = "disabled"` dans le HTML… Mais ça semble fonctionner comme ce à quoi on pourrait s'attendre…)

2022-10-03 21:25 UTC, egaillot commented on src/vues/fragments/lienNouvelOnglet.pug
> +  link(href='/statique/assets/styles/modules/lienNouvelOnglet.css', rel='stylesheet')
Je vois que ça te convient (👍)… mais je ne crois pas que ce bout de code ait changé 😉

2022-10-03 21:26 UTC, egaillot commented on src/vues/fragments/modaleNouveauService.pug
> +            .case-a-cocher
Cool ! 🙂

2022-10-03 22:26 UTC, egaillot commented on public/assets/styles/modules/lienNouvelOnglet.css
> +a.nouvel-onglet:after {
Assez tristement, l'icône ajoutée est renvoyée en début de ligne… 😓 

<img width="340" alt="Screenshot 2022-10-04 at 00 00 26" src="https://user-images.githubusercontent.com/105624/193693677-431010ff-b6ba-4209-be8d-96dffe1e9c41.png">

Je pense qu'on peut régler le problème en indiquant dans un autre sélecteur de ce fichier
```css
a.nouvel-onglet {
  display: inline-block;
}
```

(Problème : la justification à gauche est moche… Je n'ai pas de bonne réponse à ça, malheureusement. Toutefois, en revoyant la gestion des marges et des paddings dans `modale.css` – cf. commentaire correspondant – on s'en sort pas mal.)

2022-10-03 22:26 UTC, egaillot commented on public/assets/styles/modale.css
> +  padding: 0 1em 1em 0;
En faisant ça, on casse le style des autres modales.
<img width="448" alt="Screenshot 2022-10-04 at 00 10 40" src="https://user-images.githubusercontent.com/105624/193695045-cfc6b5bd-c02f-496f-8ba3-559c9ae222d6.png">

Je pense qu'il faut laisser ce `padding` comme il était.

2022-10-03 22:26 UTC, egaillot commented on public/assets/styles/modale.css
> +  padding: 0 1em 1em 0;
Si par ailleurs on enlève le `padding: 0 5em` de `.contenu-modale`, on a quelque chose qui présente plutôt bien je trouve.

2022-10-03 22:26 UTC, egaillot commented on public/assets/styles/bouton.css
> +  font-size: 1em;
Ces styles ne sont pas liés à la classe `bouton`, mais à la balise `button`.

(Note : c'est peut-être une bonne idée d'utiliser un `button` plutôt qu'un `.bouton` – même si on commence à avoir deux manière de gérer l'envoi d'un formulaire, et que ça sera bien d'homogénéiser tout ça. Pour l'instant, pourquoi pas rester comme ça effectivement.)

Toujours pour éviter les redondances, je préfèrerais qu'on attache ces trois styles à un sélecteur `button` à part.

2022-10-03 22:27 UTC, egaillot commented on public/assets/styles/formulaire.css
> +}
Merci d'avoir tenu compte de ma remarque… mais je pense avoir été mal compris : je ne suggérais pas de spécifier un « non-highlight » sur le bouton inactif, mais de ne spécifier un highlight _que_ sur les boutons _pas_ inactifs (cf. commentaire plus bas).

2022-10-04 08:10 UTC, ColinGarrigaSalaun commented on public/modules/modaleNouveauService.js
> +    }
:+1:

2022-10-04 08:18 UTC, ColinGarrigaSalaun commented on src/vues/fragments/lienNouvelOnglet.pug
> +  link(href='/statique/assets/styles/modules/lienNouvelOnglet.css', rel='stylesheet')
:+1:

2022-10-04 08:18 UTC, ColinGarrigaSalaun commented on public/assets/styles/bouton.css
> +  opacity: 1;
:+1:

2022-10-04 08:40 UTC, ColinGarrigaSalaun commented on public/assets/styles/modules/lienNouvelOnglet.css
> +a.nouvel-onglet:after {
:+1:

2022-10-04 12:38 UTC, egaillot commented on public/assets/styles/formulaire.css
> +}
Désolé – la modif que j'ai proposée ce matin n'est pas bonne (visiblement, `:not(:disabled)` n'est pas la même chose que `:enabled`) et casse des choses. Je vais m'occuper de faire un correctif.

2022-10-04 21:00 UTC, egaillot commented on public/assets/styles/bouton.css
> +.bouton:not(:disabled):hover {
J'ai ajouté cette correction – je te laisse vérifier que ça te convient.

2022-10-04 21:01 UTC, egaillot commented on public/assets/styles/modale.css
> +  text-align: left;
J'ai déplacé le style d'alignement dans ce sélecteur. Je te laisse vérifier que ça te convient.

2022-10-04 21:04 UTC, egaillot approved these changes
Je te laisse vérifier que les deux commits ajoutés te conviennent, et si c'est le cas de faire un « Squash & Merge ».

Encore merci pour ta patience et tout le travail que tu as abattu sur cette PR 🙏

2022-10-06 09:54 UTC, merged