L'annexe avec les mesures en cours
betagouv/mon-service-securise pull request #435
Opened 2022-10-19 09:17 UTC by JacquesRogueOne

dans l'objectif de réaliser une annexe avec les mesures,
J'ai ajouté les mesures en cours à la page `/:id/syntheseSecurite/annexes/mesures`

- Il n'y a pas de saut de page
- Les modalités (commentaires) des mesures n'est pas affiché
- La capture des données inclue les mesures faites et non faites pour un affichage futur

NOTE : les mesures spécifiques sont présentes

2022-10-23 21:12 UTC, egaillot commented on public/assets/styles/annexes/mesures.css
> +.mesures-par-statut li::before {
Ce sélecteur qui est surchargé en dessous me rend nerveux… Est-ce qu'on pourrait expliciter ce qui est propre au point bleu (vraisemblablement, le `height`, le `margin-right` et le `background-image` dans un sélecteur à part, typiquement `.mesures-par-statut li:not(.indispensable)::before` ?

2022-10-23 21:12 UTC, egaillot commented on public/assets/styles/palette.css
> +  --graphique-bleu-clair:var(--fond-bleu-clair);
Je serais partisan qu'on lutte contre la prolifération des couleurs en commençant à séparer les couleurs utilisées pour le site web et celles utilisées pour les documents PDF (et peut-être, a terme, séparer les deux palettes en deux fichiers CSS). Peut-être qu'on pourrait commencer ici (ou plus exactement, arrêter d'aggraver notre cas… 😓) avec l'introduction d'un `--pdf-bleu-clair` ?

2022-10-23 21:12 UTC, egaillot commented on src/modeles/mesures.js
> +          id: mesure.id,
Je ne vois pas l'utilité de passer l'identifiant à la vue… Peux-tu m'en dire plus s'il te plaît ?

2022-10-24 14:05 UTC, JacquesRogueOne commented on src/modeles/mesures.js
> +          id: mesure.id,
Oui on en a pas besoin 👍🏼

2022-10-24 14:06 UTC, JacquesRogueOne commented on test/modeles/mesures.spec.js
> +    elles('regroupe par statut les mesures', () => {
Merci pour ta patience et ta vigilance 🙏🏼

2022-10-26 09:24 UTC, ColinGarrigaSalaun commented on src/modeles/mesures.js
> +  }
C'est probablement le bon moment de déporter le code dans `MesuresGenerales` et dans `MesuresSpecifiques` tel que proposé par @egaillot. Ce refactoring facilitera la reprise du code, et préparera le refactoring plus large modifiant la hiérarchie de ces classes.

2022-10-26 09:31 UTC, ColinGarrigaSalaun requested changes
Le refactoring indiqué me semble important à faire maintenant. Cette bonne idée risque d'être oubliée et le code sera plus difficile à reprendre et à maintenir.

2022-10-27 09:37 UTC, ColinGarrigaSalaun approved these changes

2022-10-27 13:01 UTC, merged