🧹 Nettoie services créés pour les tests
betagouv/mon-service-securise pull request #534
Opened 2022-12-09 19:50 UTC by cadichris

Cette PR ajoute la possibilité de supprimer les services créés par des utilisateurs, via leur identifiant.
L'objectif est de supprimer les services existants à tort en PROD.

⚠️ Pour ne pas supprimer le service « MSS », il est possible de spécifier des identifiants de service à toujours conserver.

La suppression se déclenche par `ConsoleAdministration` :

```js
const ConsoleAdministration = require('./consoleAdministration')
const admin = new ConsoleAdministration();

const utilisateur = 'uuid-utilisateur';
const monServiceSecurise = 'uuid-mss';

admin.supprimeHomologationsDeUtilisateur(utilisateur, [monServiceSecurise])
  .then(() => console.log('OK'))
```

ℹ️  Les discussion avec @egaillot ont permis d'identifier 9 comptes utilisateurs à nettoyer via la console.

2022-12-11 17:53 UTC, egaillot requested changes
Il manque la gestion de la suppression des autorisations liées aux homologations supprimées.

2022-12-11 17:53 UTC, egaillot commented on src/depots/depotDonneesHomologations.js
> +      .map((u) => homologations(u.id).then((hs) => hs.filter((h) => h.estCreeePar(u.id))));
J'arrive un peu après la bataille, mais je pense que ce code aurait plus sa place dans `DepotDonneesAutorisations`. On pourra en reparler ensemble à l'occasion.

2022-12-11 17:53 UTC, egaillot commented on src/depots/depotDonneesHomologations.js
> +      )));
Ce n'est malheureusement pas aussi simple 😓 
- Il faut commencer par supprimer toutes les autorisations qui font référence à l'`idUtilisateur` avec `type: createur` (et dont l'homologation correspondante n'a pas pour identifiant un des `idHomologationsAConserver`)
- … puis il faut supprimer toutes les autorisations qui font référence aux homologations à supprimer où il y a des contributeur·ices
- … puis en cascade supprimer les homologations

(Note qu'il devrait y avoir un moyen de faire les deux premières étapes en une seule requête SQL.)

2022-12-11 17:53 UTC, egaillot commented on consoleAdministration.js
> +
À voir si ça te semble plus lisible – on peut écrire
```javascript
supprimeHomologationDeUtilisateur(...params) {
  return this.depotDonnees.supprimeHomologationsCreeesPar(...params);
}
```

On perd en lisibilité de l'API, on gagne en clarté que c'est une délégation. Je préfère la deuxième option, mais je suis ouvert à ce qu'on reste sur la première.

2022-12-13 09:09 UTC, cadichris commented on consoleAdministration.js
> +
Je préfère rester sur cette syntaxe.

2022-12-13 10:39 UTC, egaillot commented on src/depots/depotDonneesHomologations.js
> +      )));
En y regardant de plus près – ben si ça marche en fait 😅 Merci `supprimeHomologation` qui fait plus de choses que je ne croyais.

2022-12-13 10:42 UTC, egaillot approved these changes
👍

2022-12-13 10:47 UTC, merged