Champs requis pour les mesures spécifiques
betagouv/mon-service-securise pull request #556
Opened 2022-12-13 16:38 UTC by JacquesRogueOne

Dans la page des mesures
les mesures spécifiques sont munies de système de validation pour les champs description, statut et catégorie

- Style des select commun à tous les formulaires
- Branchement des validateur sur un conteneur
- Nouveau style du bloc

<img width="804" alt="Capture d’écran 2022-12-13 à 17 32 21" src="https://user-images.githubusercontent.com/39462397/207390131-f7b5c16d-1d65-499c-abdc-4d1ebd864a66.png">

2022-12-14 13:32 UTC, JacquesRogueOne commented
La partie du code des éléments ajoutables où on récupère des informations en jquery puis on injecte des composants html dans le dom j'ai l'impression que cette fois on lui en demande trop. J'aimerais que l'on discute de l'évolution de ces composants.

2022-12-15 14:50 UTC, cadichris commented on public/assets/styles/formulaire.css
> +  right: 15px;
Peut-être des `em` ici ?

2022-12-15 15:28 UTC, cadichris commented on public/assets/styles/homologation/mesures.css
> +  margin-bottom: 1em;
Comme vu ensemble : le `margin-bottom` peut être supprimé si on utilise un `<label>` ou `<fieldset>` qui permettent de bénéficier des structures de formulaire déjà en place.

2022-12-19 13:57 UTC, JacquesRogueOne commented on public/assets/styles/homologation/mesures.css
> +  margin-bottom: 1em;
j'ai utilisé label pour wrapper les type text et text area mais pour les radio c'est pas bon, fieldset a trop de styles définis dans mesures donc je l'ai pas utilisé et donc j'ai mis une classe _propriete-specifique_ pour y définir le margin-bottom 1em

2022-12-19 13:59 UTC, JacquesRogueOne commented
J'ai ajouté 1em d'espace à droite des input pour équilibrer avec la gauche
<img width="789" alt="Capture d’écran 2022-12-19 à 14 57 46" src="https://user-images.githubusercontent.com/39462397/208442150-9de97e4f-9234-4a8f-a2ee-e0a572c89f44.png">

2022-12-19 15:49 UTC, cadichris commented on public/homologation/mesures.js
> +  <div class="message-erreur">Ce champs est obligatoire. Veuillez le renseigner.</div>
Je crois qu'il y a un `s` en trop ici : `Ce champ est…`

2022-12-19 15:54 UTC, cadichris requested changes
La typo à corriger et ensuite c'est tout bon !

2022-12-20 14:42 UTC, cadichris approved these changes

2022-12-20 15:27 UTC, merged