Correction du bug des mesures générales indispensables
betagouv/mon-service-securise pull request #563
Opened 2022-12-14 16:12 UTC by JacquesRogueOne

Dans les annexes,
Les mesures rendues indispensables apparaissent comme recommandées (sans l'étoile)

La cause est l'instanciation dans les listeItems des objets MesureGenerale sans le paramètre `renduIndispensable`

2022-12-14 16:17 UTC, JacquesRogueOne commented
Le `renduIndispensable` est source de confusion, si vous avez des idées pour faire évoluer cela elles sont les bienvenues.

2022-12-15 09:08 UTC, cadichris commented
📆 Rendez-vous est pris ce jour à 15 h. pour une mob-review de design.

2022-12-16 10:17 UTC, cadichris requested changes
Excellent, merci pour cette nette amélioration du design !

J'ai l'impression que le premier commit `Rends les mesures générales indispensable` pourrait tout bonnement être supprimé. 
Tu confirmes ? Si oui, peux-tu le faire avant approbation ?

2022-12-19 15:35 UTC, cadichris approved these changes

2022-12-19 16:06 UTC, merged