Renommer le bouton enregistrer de description du service
betagouv/mon-service-securise pull request #58
Opened 2022-01-05 15:47 UTC by JacquesRogueOne

Dans la page description du service,
le bouton **Enregistrer** devient **Enregistrer et revenir à l'espace personnel**

2022-01-05 21:32 UTC, egaillot requested changes
Je suis très surpris de cette fonctionnalité 🤔 
- Ça me semble étrange que l'on veuille revenir à l'espace personnel après avoir modifié la description du service. 
- Ça me semble étrange que l'on veuille un comportement différent pour la création et pour la modification
- Ça me semble étrange qu'on affiche « … et revenir à l'espace personnel », et qu'on redirige l'utilisateur non pas vers cet espace, mais vers la page de synthèse de l'homologation.

… Est-ce bien ce qu'on cherche à implémenter ?

2022-01-06 16:24 UTC, jbdemaison commented
Salut, désolé on en a parlé avec Mari et j'ai oublié de vous dire : donc la solution est assez simple, à la fin de description du service (avant l'accès à la synthèse du dossier), il faut un unique bouton "VALIDER" qui mène au dossier. On oublie "enregistrer et revenir à l'espace personnel" et "suivant" (enfin "suivant" devient "VALIDER" vu que "Suivant servira ensuite à passer d'une rubrique à une autre).

2022-01-10 13:31 UTC, JacquesRogueOne commented
J'ai mis **Enregistrer** pour les déjà existantes et **Valider** pour les nouvelles

2022-01-10 17:40 UTC, egaillot approved these changes

2022-01-12 09:31 UTC, merged