Entête de l'accueil responsif
betagouv/mon-service-securise pull request #608
Opened 2023-01-06 14:50 UTC by JacquesRogueOne

Afin de rendre le site plus responsif,
L'entête a des styles différents pour 3 niveaux d'écran et un menu sandwich 🍔
<img width="374" alt="Capture d’écran 2023-01-06 à 15 44 51" src="https://user-images.githubusercontent.com/39462397/211035143-606190c4-822e-4800-92d4-11cf90a16e62.png">
<img width="367" alt="Capture d’écran 2023-01-06 à 15 44 56" src="https://user-images.githubusercontent.com/39462397/211035146-3c4682d8-c17e-4a88-976a-d8daddb66241.png">
<img width="448" alt="Capture d’écran 2023-01-06 à 15 45 06" src="https://user-images.githubusercontent.com/39462397/211035149-9a6fe4cf-b2c3-423c-bcac-f33493506534.png">
<img width="438" alt="Capture d’écran 2023-01-06 à 15 45 13" src="https://user-images.githubusercontent.com/39462397/211035156-3fef9d95-2086-4237-8dc3-430e81b3e959.png">

Notes :
- Cette PR contient un commit de débouchonnage du style de l'entête
- Pour le sandwich j'ai du faire des modifications dans l'entête desktop
- La version connecté n'est pas optimale

2023-01-09 09:23 UTC, cadichris commented on public/assets/styles/entete.css
> +header nav .bouton-fermer {
Que penserais-tu d'expliciter également que `.sandwich` est `display:none` ?

2023-01-09 09:31 UTC, cadichris commented on public/assets/styles/entete.responsive.css
> +    height: 2em;
Vu ensemble : en mobile `2em` c'est un peu gros.

2023-01-09 09:54 UTC, cadichris commented on public/assets/styles/entete.responsive.css
> +    width: -moz-fit-content;
Même remarque pour le `-moz`, voir si c'est utile.

2023-01-09 09:57 UTC, cadichris commented on public/assets/styles/entete.responsive.css
> +  }
Vu ensemble : pourquoi pas avoir une classe css `avec-separateur-en-mobile` qui ajouterait la `border-bottom` uniquement dans les CSS `.responsive`.
Et appliquer cette classes sur les `a` du menu.

2023-01-09 15:35 UTC, JacquesRogueOne commented on public/assets/styles/entete.css
> +header nav .bouton-fermer {
ok 👍🏼

2023-01-09 15:42 UTC, JacquesRogueOne commented on public/assets/styles/entete.responsive.css
> +    height: 2em;
je suis passé en 1.5em 👍🏼

2023-01-10 09:16 UTC, cadichris commented on public/modules/interactions/brancheMenuSandwich.js
> +  const interupteurVisible = (visible) => {
Petite typo ici : `interrupteur` avec 2 `r`.

2023-01-10 09:16 UTC, cadichris requested changes
Ça rend super bien !
La petite typo à corriger et c'est tout bon.

2023-01-10 09:55 UTC, cadichris approved these changes

2023-01-10 09:57 UTC, merged