Menu contextuel de suppression de service
betagouv/mon-service-securise pull request #640
Opened 2023-01-23 14:16 UTC by JacquesRogueOne

Dans la feature de suppression,

Nous avons ajouté des liens des suppression dans l'espace personnel.
On clique sur les 3 points -> affiche un menu avec supprimer -> on clique dans ce menu -> ça affiche la modale de suppression

note : nous avons ajouté un masque non cliquable sous le menu là où est le service
<img width="484" alt="Capture d’écran 2023-01-23 à 15 15 39" src="https://user-images.githubusercontent.com/39462397/214061619-c1b4fe55-8cf6-4079-86f6-74c99d58a8fa.png">

2023-01-23 14:30 UTC, cadichris commented
Remplacée par #641.

2023-01-23 14:30 UTC, cadichris commented
Oops désolé @JacquesRogueOne, mauvaise manipulation.

2023-01-23 15:16 UTC, cadichris commented
🐞 Avec plusieurs menus contextuels ouverts, c'est le dernier qui « écrase » les autres.

Reproduction :
 - avoir 3 services sur son tableau de bord : A, B et C.
 - ouvrir le menu contextuel de A, cliquer « Supprimer » : la modale montre bien le nom du service A
 - fermer la modale (avec la croix)
 - ouvrir le menu contextuel de B et celui de C (arrivé ici les **trois** menus sont ouverts)
 - cliquer sur « supprimer » du service A
 
Attendu : la modale montre le nom du service A
Observé : la modale montre le nom du service C. C'est le nom du service dont le menu a été ouvert en dernier.

TODO :
 - quand on ouvre un menu, ça ferme tous les autres éventuellement ouverts avant d'ouvrir le nouveau.

2023-01-23 15:20 UTC, cadichris commented
### Un contributeur a quand même le menu « Supprimer »

Je peux cliquer « Supprimer » sur les services dont je ne suis pas créateur. 
À l'écran on a l'impression qu'il ne « se passe rien » puisque le serveur renvoie une `403` qui est silencieuse pour la modale de suppression.

TODO : masquer « supprimer » pour ceux qui ne sont pas créateurs.

2023-01-23 15:33 UTC, cadichris requested changes
Que penses-tu de :
 - dans cette PR – traiter le bug https://github.com/betagouv/mon-service-securise/pull/640#issuecomment-1400520788
 - dans cette PR – faire le renommage de `.options`

Gérer le masquage de « supprimer » pour les contributeurs dans une autre PR.

2023-01-23 17:05 UTC, JacquesRogueOne commented on public/espacePersonnel.js
> +    $bouton.off();
Pour éviter le cas où on ouvre plusieurs modales sans les fermer -> ce qui entrainait la suppression de plusieurs services (j'en ai fait les frais)

2023-01-24 07:52 UTC, cadichris commented on public/espacePersonnel.js
> +    $bouton.off();
Je ne comprends pas ce point, car je ne comprends pas comment on peut ouvrir plusieurs modales sans les fermer. Discutons-en 🙏

2023-01-24 14:01 UTC, JacquesRogueOne commented on public/espacePersonnel.js
> +    $bouton.off();
Nouvelle mise à jour : 
- J'ai changé le sélecteur de menu contextuel dans brancheMenuContextuelService.js ligne 1 pour un objet $menuContextuel ce qui conserve le contexte du service
- j'ai ajouté un .off('click') avant le on('click') brancheMenuContextuelService.js ligne 17 car sinon on empilait les onClick en cliquant sur les 3 points

2023-01-24 15:36 UTC, cadichris approved these changes
C'est tout bon !

2023-01-24 16:19 UTC, merged