Affiche toujours les « … » sur fond blanc
betagouv/mon-service-securise pull request #668
Opened 2023-02-07 14:41 UTC by cadichris

Cette PR ajoute un fond blanc aux « … » ce qui donne 👇 

![image](https://user-images.githubusercontent.com/24898521/217275837-b222c394-031e-4dc5-af95-13b92e9fdc18.png)

2023-02-07 14:55 UTC, egaillot requested changes

2023-02-07 15:11 UTC, cadichris commented on public/assets/styles/espacePersonnel.css
> +  background-color: #fff;
Merci ! C'est corrigé.

2023-02-07 15:12 UTC, cadichris commented on public/assets/styles/espacePersonnel.css
> +  background-color: var(--fond-pale);
Ici le `background-color: inherit;` est impossible car ça donne une couleur gris foncé lorsque le menu contextuel est ouvert : ça `inherit` la couleur de fond du masque gris foncé.

2023-02-09 09:27 UTC, egaillot approved these changes

2023-02-09 09:27 UTC, egaillot commented on public/assets/styles/espacePersonnel.css
> +  background-color: var(--fond-pale);
Mouais… J'ai l'impression qu'on devrait pouvoir faire plus simple – mais je n'ai pas de bonne idée 😓 Laissons comme ça pour l'instant.

2023-02-09 10:06 UTC, merged