Page étape avis sans possibilité d'ajouter des éléments
betagouv/mon-service-securise pull request #757
Opened 2023-03-16 15:20 UTC by JacquesRogueOne

Dans le parcours d'homologation,
La future étape 2 est pas encore accessible,
Ce dev est le corps d'une page non liée au parcours

Notes : 
- pour voir la page il faut modifier les donneesReferentiel en ajoutant `{ numero: 2, libelle: 'Avis', id: 'avis' },` à l'objet etapesParcoursHomologation
- Il ne se passe rien quand on clique sur ajouter un élément car les éléments ajoutables coté clients ne sont pas encore présent
- L'enregistrement à la soumission du formulaire n'est pas présent non plus

<img width="540" alt="Capture d’écran 2023-03-16 à 16 19 30" src="https://user-images.githubusercontent.com/39462397/225663674-103efaf2-f73a-4fb9-bb26-f96a030f666e.png">

2023-03-17 09:26 UTC, CadiChris requested changes
Merci ! Revue ensemble en binôme.

2023-03-17 09:26 UTC, CadiChris commented on src/vues/service/etapeDossier/avis.pug
> +  +elementsAjoutablesAvisUtilisateur(service.dossierCourant().avis.avis)
Vu ensemble : renommer en `elementsAjoutablesAvis`

2023-03-17 09:26 UTC, CadiChris commented on src/referentiel.js
> +    statutAvisDossierHomologation,
Typo ici : `statutS` avec un `s`.

2023-03-17 09:26 UTC, CadiChris commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +mixin elementsAjoutablesAvisUtilisateur(donneesAvisUtilisateurs = [])
Renommer le paramètre en `donneesAvis`.

2023-03-17 09:26 UTC, CadiChris commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +  .elements-ajoutables#avis-utilisateurs
Utiliser `#avis`

2023-03-17 09:26 UTC, CadiChris commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +      +avisUtilisateur
Renommer en `+unAvis`

2023-03-17 09:26 UTC, CadiChris commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +      +avisUtilisateur(avisUtilisateur, index)
Je propose un changement de structure : commencer par établir une liste des avis, avec potentiellement un ajout d'un avis vide, puis afficher cette liste.

```js
const avis = donneesAvis || [{index: 0}]
+avisUtilisateur(avis)
```

2023-03-17 09:26 UTC, CadiChris commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +    div(class = `element-avis-utilisateur-${index}`)
Utiliser `element-un-avis-${index}`

2023-03-17 09:26 UTC, CadiChris commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +          label.champ-texte Prénom Nom du collaborateur métier ou techniques renseignant l'avis
Un `s` en trop sur `techniqueS`.

2023-03-17 09:26 UTC, CadiChris commented on public/assets/styles/etapesDossier/avis.css
> +  height: 6em;
Essaye `rows: 4` ou `5` peut-être ? Il me semble que ça existe. Ou alors ça sera dans le pug.

2023-03-17 13:53 UTC, JacquesRogueOne commented on src/referentiel.js
> +    statutAvisDossierHomologation,
Corrigé dans #759

2023-03-17 14:15 UTC, JacquesRogueOne commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvisUtilisateur.pug
> +      +avisUtilisateur(avisUtilisateur, index)
J'ai mis ça
```js
- 
  if (Array.isArray(donneesAvis) && donneesAvis.length === 0) {
    donneesAvis.push({})
  }
each donneesUnAvis, index in donneesAvis 
  +unAvis(donneesUnAvis, index)
```

2023-03-17 14:22 UTC, JacquesRogueOne commented on public/assets/styles/etapesDossier/avis.css
> +  height: 6em;
Malheureusement il y a un style `height: 10em` dans formulaire.css qui est plus fort que l'attribut rows de textarea
Je laisse le height: 6em

2023-03-17 15:27 UTC, JacquesRogueOne commented on src/vues/fragments/elementsAjoutables/elementsAjoutablesAvis.pug
> +              nom = `prenomNom-un-avis-${index}`,
doit être name

2023-03-20 09:06 UTC, CadiChris approved these changes
Merci !

2023-03-20 09:19 UTC, merged