Permets la soumissions du formulaire des avis
betagouv/mon-service-securise pull request #762
Opened 2023-03-17 15:19 UTC by JacquesRogueOne

Dans le parcours d'homologation,
La future étape 2 est pas encore accessible,
Ici on permet l'enregistrement des avis

NOTES :

pour voir la page il faut modifier les donneesReferentiel en ajoutant { numero: 2, libelle: 'Avis', id: 'avis' }, à l'objet etapesParcoursHomologation

2023-03-17 15:58 UTC, CadiChris requested changes

2023-03-17 15:58 UTC, CadiChris commented on public/homologation/etapesDossier.js
> +const action = (idEtape, idService, selecteurFormulaire) => {
Plutôt que de faire grossir cette fonction, on pourrait mettre le code de soumission dans `soumissionEtapeAvis.js` ?

2023-03-17 15:58 UTC, CadiChris commented on public/modules/arrangeParametresAvis.mjs
On pourrait mettre ce code dans `soumissionEtapeAvis.js` ?

2023-03-17 16:32 UTC, JacquesRogueOne commented on test_public/modules/arrangeParametresAvis.spec.mjs
> +  it('arrange les prénom et nom dans un tableau de collaborateurs', () => {
Quand j'ai écrit j'ai pensé `Les (prénom et nom)` je vais changer pour `le prénom et le nom`

2023-03-21 13:49 UTC, CadiChris commented on test_public/modules/soumissionEtapeAvis.spec.mjs
> +    ]);
Que penses-tu d'une assertion sur l'objet en entier :

```js
expect(parametresArranges.).to.eql({
   avis : [{ collaborateurs: ['Jean'] }]
});
```

2023-03-21 15:37 UTC, merged