Modifications des textes dans plusieurs pages
betagouv/mon-service-securise pull request #98
Opened 2022-01-19 14:16 UTC by JacquesRogueOne

Anciennement **Plusieurs modifs editos #87** + ajustement des marges au-dessus des titres

> **Plusieurs modifs editos #87**
> - Modifications éditos détaillées dans les commits.
> - Notez la suppression des titres h2 à l'intérieur des rubrique suite à la disparition de la colonne de gauche dans le dossier  de synthèse.
> - Ajout d'un icône alarme en vue de son intégration (pas urgente) en haut de la modale "Besoins de sécurité élevés".

2022-01-25 10:45 UTC, egaillot commented
Concernant le nom du fichier de l'icône d'alerte, je préfèrerais qu'on mette comme nom la nature de l'icône, plutôt que la fonction qu'elle symbolise. Ainsi, la nommer `icone_gyrophare.svg` plutôt que `icone_besoins_secu_eleves.svg`.

2022-01-25 11:18 UTC, egaillot requested changes

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/avisExpertCyber.pug
> +        titre: "Durée proposée de l'homologation",
Les réponses (« dans six mois » / « dans un an » / « dans deux ans ») ne sont plus en cohérence. Plutôt que « Durée proposée… dans six mois », il faudrait « Durée proposée… six mois »

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/avisExpertCyber.pug
> +        titre: "Spécialiste cybersécurité",
Le fait qu'on supprime le mot « Avis » rend les réponses proposées (« avis favorable » / « avis défavorable ») un peu étranges… Je suggère qu'on remette « Avis du spécialiste cybersécurité » ou qu'on change les réponses en « émet un avis favorable » / « émet un avis défavorable » si on souhaite garder une écriture épicène.

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/caracteristiquesComplementaires.pug
> +    h2.titre-page Caractéristiques complémentaires
Cf. remarques plus haut

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/mesures.pug
> +    h2.titre-page Mesures de sécurité
Cf. remarques plus haut

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/partiesPrenantes.pug
> +    h2.titre-page Parties prenantes
Cf. remarques plus haut

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/risques.pug
> +    h2.titre-page Risques de sécurité
Cf. remarques plus haut

2022-01-25 11:18 UTC, egaillot commented on src/vues/homologation/risques.pug
> +      Évaluez le niveau de gravité pour votre service numérique des risques les plus courants identifiés par l'ANSSI.
On dirait qu'il manque quelque chose après « À partir des risques ».

2022-01-25 11:18 UTC, egaillot commented on src/vues/index.pug
> -    | Tenez-moi au courant de l'avancée du projet !
En supprimant ce bouton, on a une zone « fond pâle » avec rien dedans. C'est lié au `padding-bottom: 5em;` spécifié pour le sélecteur `main` – qui a du sens pour le reste du site. Peut-être qu'on pourrait ajouter dans `index.css` un `main.page-accueil { padding-bottom: 0; }` ?

2022-01-25 11:18 UTC, egaillot commented on src/vues/questionsFrequentes.pug
>          h2#responsable.
L'ancre n'est pas la bonne. Il faudrait corriger en `h2#services-concernes.`.

2022-01-25 11:18 UTC, egaillot commented on src/vues/questionsFrequentes.pug
>          h2#services-concernes.
L'ancre n'est pas la bonne. Il faudrait corriger en `h2#responsable.`.

2022-01-26 09:56 UTC, JacquesRogueOne commented on src/vues/homologation/caracteristiquesComplementaires.pug
> +    h2.titre-page Caractéristiques complémentaires
j'ai remis les blocs dans l'ordre et les liens (en haut de la page) dans le même ordre
1. Responsable
2. RGS

2022-01-26 09:57 UTC, JacquesRogueOne commented on src/vues/questionsFrequentes.pug
>          h2#responsable.
j'ai remis les blocs dans l'ordre et les liens (en haut de la page) dans le même ordre
1. Responsable
2. RGS

2022-01-28 13:57 UTC, egaillot commented on src/vues/homologation/avisExpertCyber.pug
> +        titre: "Spécialiste cybersécurité",
Vu avec @jbdemaison : on laisse comme ça.

2022-01-28 14:01 UTC, egaillot commented on src/vues/homologation/risques.pug
> +      Évaluez le niveau de gravité pour votre service numérique des risques les plus courants identifiés par l'ANSSI.
Vu avec @jbdemaison : on enlève la ligne 11.

2022-01-28 14:04 UTC, egaillot commented on src/vues/questionsFrequentes.pug
>          h2#responsable.
Vu avec @jbdemaison : c'est bien d'abord la question sur le responsable, puis la question sur les services.

2022-01-28 14:06 UTC, egaillot commented on src/vues/homologation/avisExpertCyber.pug
> +        titre: "Durée proposée de l'homologation",
Vu avec @jbdemaison : on rétablit « Renouvellement » pour l'instant.

2022-01-28 14:06 UTC, egaillot commented on public/assets/styles/index.css
> +}
J'ai corrigé le problème.

2022-01-28 14:07 UTC, egaillot approved these changes

2022-01-31 14:51 UTC, merged